#data_dir: "/Users/smohammed/Documents/GitHub/Code/Support Vectors/LLM Bootcamp/Vector-database/corpus"
data_dir: "/home/transformers/corpus"
db_config:
   {
      host: localhost, 
      user: transformers, 
      password: supportvectors.123, 
      database: vectordb
   }
db_url: "mariadb+mariadbconnector://transformers:supportvectors.123@localhost/vectordb"
producer: {
    'bootstrap.servers': 'localhost:9092',  # Replace with your Kafka broker(s)
    'client.id': 'python-producer'
   }
consumer: {
    'bootstrap.servers': 'localhost:9092',  # Replace with your Kafka broker(s)
    'group.id': 'python-consumer',
    'auto.offset.reset': 'earliest'
}
kafka-topic: "tp-list-files"
embedding_model: "distilbert-base-nli-mean-tokens"